#!/bin/bash -eu


exoauth () {
    case $1 in
        prod)
            echo 'logging into prod account'
            get_op_item 'exoscale-prod-api-key'
            ;;
        dev)
            echo 'logging into dev account'
            get_op_item 'exoscale-dev-api-key'
            ;;
        *)
            echo "no environment given"
            return 1
            ;;
    esac
    aws sso login --profile nightingale-prod
    export PKR_VAR_EXO_API_KEY="${OP_ITEM_USERNAME}"
    export PKR_VAR_EXO_API_SECRET="${OP_ITEM_PASSWORD}"
    export EXOSCALE_API_KEY="${OP_ITEM_USERNAME}"
    export EXOSCALE_API_SECRET="${OP_ITEM_PASSWORD}"
}
